"""Update Tables

Revision ID: 581d99c452db
Revises: c9a18e6733bd
Create Date: 2026-02-01 14:24:18.326406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581d99c452db'
down_revision: Union[str, Sequence[str], None] = 'c9a18e6733bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

accounttype_enum = sa.Enum('CHECKING', 'SAVINGS', name='accounttype')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    # Placeholder member so existing accounts can reference member_id
    op.execute(
        "INSERT INTO members (id, first_name, last_name, email, phone, address, city, state, zip, country) "
        "VALUES (1, 'System', 'Placeholder', 'system@placeholder.local', '', '', '', '', '', '')"
    )
    # Create PostgreSQL enum type before adding column that uses it
    accounttype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('accounts', sa.Column('account_type', accounttype_enum, nullable=False, server_default=sa.text("'CHECKING'::accounttype")))
    op.add_column('accounts', sa.Column('member_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('accounts', sa.Column('account_number', sa.String(), nullable=False, server_default=sa.text("'00000000'")))
    op.create_foreign_key('accounts_member_id_fkey', 'accounts', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_member_id_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'account_number')
    op.drop_column('accounts', 'member_id')
    op.drop_column('accounts', 'account_type')
    accounttype_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
